---
- name: Create destination directory
  file:
    name: "{{ DEST_DIR }}"
    state: directory
    mode: 0655
  register: res

- name: Spin up ELK stack if directory "{{ DEST_DIR }}" not exists
  block:

    - name: Clone ELK git repository
      git:
        repo: https://github.com/deviantony/docker-elk.git
        dest: "{{ DEST_DIR }}"
        clone: yes

    - name: Copy kibana config
      template:
        src: kibana.j2
        dest: "{{ DEST_DIR }}/kibana/config/kibana.yml"

    - name: Copy logstash config
      template:
        src: logstash.j2
        dest: "{{ DEST_DIR }}/logstash/pipeline/logstash.conf"

    - name: Copy docker-compose file
      template:
        src: docker-compose.j2
        dest: "{{ DEST_DIR }}/docker-compose.yml"

    - name: Compose up ELK stack
      docker_service:
        project_src: "{{ DEST_DIR }}"
        state: present
      notify: restart nginx

  when: res.changed != False
