---
- name: Clone ELK git repository
  git:
    repo: https://github.com/deviantony/docker-elk.git
    dest: "{{ DEST_DIR }}"

- name: Copy kibana config
  template:
    src: kibana.j2
    dest: "{{ DEST_DIR }}/docker-elk/kibana/config/kibana.yml"

- name: Copy docker-compose file
  template:
    src: docker-compose.j2
    dest: "{{ DEST_DIR }}/docker-compose.yml"

- name: Compose uo ELK stack
  docker_service:
    project_src: "{{ DEST_DIR }}"
    state: present
